// Generated by CoffeeScript 1.6.3
var GOAL, GOAL_URL, GetCSVLines, PROGRESS, PROGRESS_URL;

GOAL_URL = "https://dl.dropboxusercontent.com/u/46323284/personal_goal.csv";

PROGRESS_URL = "https://dl.dropboxusercontent.com/u/46323284/personal_data.csv";

GetCSVLines = function(csv) {
  var fields, lines;
  lines = csv.split('\n');
  fields = _(lines[0].split(',')).map(function(item) {
    return item.toLowerCase();
  });
  lines = lines.slice(1);
  return [fields, lines];
};

GOAL = [];

PROGRESS = [];

/*
$.when(
    $.get(GOAL_URL, (file) ->
        [fields, lines] = GetCSVLines(file)
        _(lines).each (line) ->
            vals = line.split ','
            obj = _.object _.zip(fields, vals)
            GOAL.push obj
    ),
    $.get(PROGRESS_URL, (file) ->
        [fields, lines] = GetCSVLines(file)
        _(lines).each (line) ->
            vals = line.split ','
            obj = _.object _.zip(fields, vals)
            obj.data = _(vals[1..]).map (val) -> val.length
            PROGRESS.push obj
    )
).then(
    () -> # on success
        console.log "loading OK"
        window.PlotPunchCard GOAL, PROGRESS
    () ->  # on error
)
*/


/*
//@ sourceMappingURL=file.map
*/
